/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vivatech.controller.corporate;

import com.vivatech.config.Response;
import com.vivatech.model.corporate.Card;
import com.vivatech.repository.corporate.CardRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

/**
 *
 * @author KALAM
 */
@CrossOrigin(origins = "*", allowedHeaders = "*")
@Controller // This means that this class is a Controller
@RequestMapping(path = "/card") // This means URL's start with /demo (after Application path)
public class CardController {
  @Autowired // This means to get the bean called categoriesRepository
             // Which is auto-generated by Spring, we will use it to handle the data
  private CardRepository categoriesRepository;

  @PostMapping(path = "/add") // Map ONLY POST Requests
  public @ResponseBody Response addNewCard(@RequestBody Card in) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request
    try {
      categoriesRepository.save(in);

    } catch (Exception e) {
      // TODO: handle exception
      return new Response("", e.getMessage());
    }
    return new Response("SUCCESS", "");

  }

  @PostMapping(path = "/update") // Map ONLY POST Requests
  public @ResponseBody Response updateCategorie(@RequestBody Card in) {
    try {

      categoriesRepository.save(in);

    } catch (Exception e) {
      // TODO: handle exception
      return new Response("", e.getMessage());
    }

    return new Response("SUCCESS", "");

  }

  @PostMapping(path = "/delete") // Map ONLY POST Requests
  public @ResponseBody Response deleteCard(@RequestBody Integer id) {

    try {

      categoriesRepository.deleteById(id);

    } catch (Exception e) {

      return new Response("", e.getMessage());
    }

    return new Response("SUCCESS", "");
  }

  @GetMapping(path = "/view")
  public @ResponseBody Iterable<Card> getAllCard() {
    // This returns a JSON or XML with the categories
    return categoriesRepository.findAll();
  }
}

