package com.vivatech.controller.cms;

import com.vivatech.model.cms.Contenttypes;
import com.vivatech.repository.cms.ContenttypesRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@CrossOrigin(origins = "*", allowedHeaders = "*")
@Controller	// This means that this class is a Controller
@RequestMapping(path="/contenttypes") // This means URL's start with /demo (after Application path)
public class ContenttypesController {
	@Autowired // This means to get the bean called ContenttypesRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private ContenttypesRepository contenttypesRepository;

	@PostMapping(path="/add") // Map ONLY POST Requests
	public @ResponseBody String addNewContenttypes (@RequestBody Contenttypes in) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Contenttypes n = new Contenttypes();
		n.setId(in.getId());
		n.setType(in.getType());

		contenttypesRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<Contenttypes> getAllContenttypes() {
		// This returns a JSON or XML with the users
		return contenttypesRepository.findAll();
	}
}
