package com.vivatech.controller.cms;

import com.vivatech.model.cms.Languages;
import com.vivatech.repository.cms.LanguagesRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@CrossOrigin(origins = "*", allowedHeaders = "*")
@Controller	// This means that this class is a Controller
@RequestMapping(path="/languages") // This means URL's start with /demo (after Application path)
public class LanguagesController {
	@Autowired // This means to get the bean called LanguagesRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private LanguagesRepository languagesRepository;

	@PostMapping(path="/add") // Map ONLY POST Requests
	public @ResponseBody String addNewLanguages (@RequestBody Languages in) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Languages n = new Languages();
		n.setId(in.getId());
		n.setLanguage(in.getLanguage());

		languagesRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<Languages> getAllLanguages() {
		// This returns a JSON or XML with the languages
		return languagesRepository.findAll();
	}
}
