package com.vivatech.controller.cms;

import com.vivatech.model.cms.Usercontents;
import com.vivatech.repository.cms.UsercontentsRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@CrossOrigin(origins = "*", allowedHeaders = "*")
@Controller	// This means that this class is a Controller
@RequestMapping(path="/usercontents") // This means URL's start with /demo (after Application path)
public class UsercontentsController {
	@Autowired // This means to get the bean called userRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private UsercontentsRepository usercontentsRepository;

	@PostMapping(path="/add") // Map ONLY POST Requests
	public @ResponseBody String addNewUsercontents (@RequestBody Usercontents in) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		// Usercontents n = new Usercontents();
		// n.setUserid(in.getUserid());
		// n.setContentid(in.getContentid());

		// usercontentsRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Usercontents getAllUsercontents(@RequestBody String contentid) {
		// This returns a JSON or XML with the users
		return usercontentsRepository.findByUsercontentsIdentityContentid(contentid);
	}
}
