package com.vivatech.service;

import java.util.ArrayList;

import org.springframework.beans.factory.annotation.Autowired;
// import org.springframework.security.core.userdetails.User;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.stereotype.Service;

import com.vivatech.model.cms.Users;
import com.vivatech.repository.cms.UsersRepository;

@Service
public class JwtUserDetailsService implements UserDetailsService {

  // @Autowired
  // private UserDao userDao;
  @Autowired // This means to get the bean called userRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  private UsersRepository usersRepository;

  // @Autowired
  // private PasswordEncoder bcryptEncoder;

  @Override
  public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
    Users user = usersRepository.findByUsername(username);
		if (user == null) {
			throw new UsernameNotFoundException("User not found with username: " + username);
		}
		return new org.springframework.security.core.userdetails.User(user.getUsername(), user.getPasswordhash(),
				new ArrayList<>());
	}

	// public DAOUser save(UserDTO user) {
	// 	DAOUser newUser = new DAOUser();
	// 	newUser.setUsername(user.getUsername());
	// 	newUser.setPassword(bcryptEncoder.encode(user.getPassword()));
	// 	return userDao.save(newUser);
	// }
}
